code is not always there
If there's an error in my `auth` method for example, I can't see the error because the sendError function fails :(

TypeError: Cannot call method 'toString' of undefined
     at ServerResponse.writeHead (http.js:1178:45)
     at ServerResponse.res.writeHead 
     at sendError (packages/cfs:http-methods/http.methods.server.api.js:280)
     at packages/cfs:http-methods/http.methods.server.api.js:565